### PR TITLE
Update solidity

### PR DESCRIPTION
**Pull request by andresilva**
Update solidity because of constructor bug in 0.4.22.

### CODE REVIEW

**Comment by jimmygchen** [comment]
@andresilva @kirushik
I'm not able to get the latest version of `ExampleBlockReward` contract (with the `constructor`) to work in parity v1.11.5. (Compiled with Solidity 0.4.24)

However, after removing the constructor argument and setting the system address in the block reward contract, the system call works fine. 

I understand that it's an example and not for production - just wanted to confirm that is the system address is not passed from Parity and required to be added to the implementing contract?

Thanks!

**Comment by andresilva** [comment]
@jchen86 How did you deploy the original contract in parity? If you deployed by using the genesis state in the chain spec then you must concatenate the encoded arguments (i.e. system address) to the contract bytecode. I added some notes about this in the `ValidatorSet` docs (https://wiki.parity.io/Validator-Set#contracts) but I should also add it to the block reward contract docs.

**Comment by jimmygchen** [comment]
@andresilva Yes, I deployed using the genesis state in the chain spec. Appending the encoded constructor arguments worked! 
Thanks.

**Review by kirushik — APPROVED** [review]
I've finally got around to review my share of contracts code.

Sorry for the delay!

**Pull request merged**
